weights: ./work_dir/ablation/CS_CP/best.pt #weight path
# feeder
feeder: ./feeder.feeder.Feeder
test_feeder_args:
  data_path: ../st-gcn/data/NTU-RGB-D-120/xsub/mh_set/val_hi.npy
  label_path: ../st-gcn/data/NTU-RGB-D-120/xsub/mh_set/val_hi_label.pkl

# model
model: net.st_gcn.Model
save_result: True
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    mode_test: 'ntu-rgb+d'

# test
phase: test
device: 0
test_batch_size: 10
