# command line: main.py recognition -c config/MA_Mode/CS/cp.yaml

base_lr: 0.01
batch_size: 256
config: config/MA_Mode/CS/cp.yaml
debug: false
device: 0
eval_interval: 5
feeder: ./feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        mode_test: cp
        strategy: spatial
    in_channels: 3
    num_class: 120
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 10
save_log: true
save_result: true
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 10
test_feeder_args:
    data_path: ../st-gcn/data/NTU-RGB-D-120/xsub/mh_set/val_hi.npy
    label_path: ../st-gcn/data/NTU-RGB-D-120/xsub/mh_set/val_hi_label.pkl
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: ./work_dir/ablation/CS_CP/best.pt
work_dir: ./work_dir/tmp
