# weights: ./models/st_gcn.ntu-xsub.pt
# weights: ./work_dir/recognition/ntu-xsub/ST_GCN/epoch60_model.pt
weights: ./work_dir/recognition/ntu-xsub/ST_GCN_newModel/last.pt # 82.11%
# feeder
feeder: ./feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU120-XSUB/val_hi.npy
  label_path: ./data/NTU120-XSUB/val_hi_label.pkl

# model
model: net.st_gcn.Model
save_result: True
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
phase: test
device: 0
test_batch_size: 10
